export const ROUTES = {
  HOME: '/',
  FAQ: '/faq',
  CONTACT_US: '/contact-us',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  JOB_APPLICATION: '/job',
  FIND_JOB: '/find-job',
  HIRE_NOW: '/hire',
  JOB_RESULTS: '/job-results',
  JOB_LISTING: '/job-listing',
  REGISTER: '/register',
  BECOME_EMPLOYER: '/become-employer',
  FORGOT_PASSWORD: '/forgot',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  EMAIL_CONFIRM: '/confirm',
  CHANGE_PASSWORD: '/change-password',
  PRICING: '/pricing',
  ABOUT_US: '/about-us',
  PRIVACY_POLICY: '/privacy',
};
